spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/iot_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123123123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# MQTT
mqtt.broker=tcp://10.240.25.150:1884
mqtt.client-id=iot-backend
mqtt.topic.sensor=sensor_data
mqtt.topic.control=device_control
mqtt.topic.response=device_response
mqtt.username=lethithutrang
mqtt.password=b23dccn838